#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Inteli'
        hostname: ubuntu
        username: inteli
        password: '$6$FhcddHFVZ7ABA4Gi$YmScvYxkPo4GN2v2EFACJWFW5zzFgBk908HoqtqT0K0Nv/RLYxvSEdIkMslG9ES.TimNtd1VhEHYv5P8oxzGe/'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"
    packages:
        - git
        - wget
        - curl
    snaps:
        - name: mysql-workbench-community
        - name: beekeeper-studio
        - name: slack
        - name: code
          classic: true
    late-commands:
        - curtin in-target -- wget -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        - curtin in-target -- apt install -y /tmp/chrome.deb && rm -rf /tmp/chrome.deb

        - curtin in-target -- apt update && apt install -y curl
        - curtin in-target -- su - inteli -c "curl https://get.volta.sh | bash"
        - curtin in-target -- su - inteli -c ". ~/.profile && volta install node@18"
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
